//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace org::alljoyn::example::Robot;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
IAsyncOperation<RobotLeftResult^>^ RobotServiceEventAdapter::LeftAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RobotLeftCalledEventArgs(info);
    LeftCalled(this, args);
    return RobotLeftCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RobotRightResult^>^ RobotServiceEventAdapter::RightAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RobotRightCalledEventArgs(info);
    RightCalled(this, args);
    return RobotRightCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RobotForwardResult^>^ RobotServiceEventAdapter::ForwardAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RobotForwardCalledEventArgs(info);
    ForwardCalled(this, args);
    return RobotForwardCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RobotBackwardResult^>^ RobotServiceEventAdapter::BackwardAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RobotBackwardCalledEventArgs(info);
    BackwardCalled(this, args);
    return RobotBackwardCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RobotStopResult^>^ RobotServiceEventAdapter::StopAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RobotStopCalledEventArgs(info);
    StopCalled(this, args);
    return RobotStopCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RobotAutomaticResult^>^ RobotServiceEventAdapter::AutomaticAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RobotAutomaticCalledEventArgs(info);
    AutomaticCalled(this, args);
    return RobotAutomaticCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RobotManualResult^>^ RobotServiceEventAdapter::ManualAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RobotManualCalledEventArgs(info);
    ManualCalled(this, args);
    return RobotManualCalledEventArgs::GetResultAsync(args);
}

// Property Reads
// Property Writes
