//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace com::glovebox::rover::RPIROBOTAllJoyn::MainInterface;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
IAsyncOperation<MainInterfaceAutonomousResult^>^ MainInterfaceServiceEventAdapter::AutonomousAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new MainInterfaceAutonomousCalledEventArgs(info);
    AutonomousCalled(this, args);
    return MainInterfaceAutonomousCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<MainInterfaceBackwardResult^>^ MainInterfaceServiceEventAdapter::BackwardAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new MainInterfaceBackwardCalledEventArgs(info);
    BackwardCalled(this, args);
    return MainInterfaceBackwardCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<MainInterfaceForwardResult^>^ MainInterfaceServiceEventAdapter::ForwardAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new MainInterfaceForwardCalledEventArgs(info);
    ForwardCalled(this, args);
    return MainInterfaceForwardCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<MainInterfaceLeftResult^>^ MainInterfaceServiceEventAdapter::LeftAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new MainInterfaceLeftCalledEventArgs(info);
    LeftCalled(this, args);
    return MainInterfaceLeftCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<MainInterfaceManualResult^>^ MainInterfaceServiceEventAdapter::ManualAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new MainInterfaceManualCalledEventArgs(info);
    ManualCalled(this, args);
    return MainInterfaceManualCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<MainInterfaceRightResult^>^ MainInterfaceServiceEventAdapter::RightAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new MainInterfaceRightCalledEventArgs(info);
    RightCalled(this, args);
    return MainInterfaceRightCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<MainInterfaceStopResult^>^ MainInterfaceServiceEventAdapter::StopAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new MainInterfaceStopCalledEventArgs(info);
    StopCalled(this, args);
    return MainInterfaceStopCalledEventArgs::GetResultAsync(args);
}

// Property Reads
// Property Writes
